"""consolidate resume_profiles and job_requirements into JSONB, link evaluations to candidate directly

Revision ID: 4eb190e430d8
Revises: 1a0e63a1620a
Create Date: 2026-08-23 12:36:59.799408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4eb190e430d8'
down_revision: Union[str, None] = '1a0e63a1620a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # This project has no production data yet — only dev/test rows from
    # local verification. The new NOT NULL columns below (structured_data,
    # extraction_version, llm_model, candidate_id) have no sensible
    # default for existing rows, so those rows are cleared rather than
    # backfilled with placeholder data. FK-safe order: children first.
    op.execute("DELETE FROM evaluations")
    op.execute("DELETE FROM resumes")
    op.execute("DELETE FROM job_descriptions")
    op.execute("DELETE FROM candidates")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_profiles')
    op.drop_table('job_requirements')
    op.add_column('evaluations', sa.Column('candidate_id', sa.UUID(), nullable=False))
    op.add_column('evaluations', sa.Column('llm_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('evaluations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('uq_evaluations_resume_job_scoring_version', 'evaluations', type_='unique')
    op.create_index('ix_evaluations_candidate_id', 'evaluations', ['candidate_id'], unique=False)
    op.create_index('ix_evaluations_job_description_id', 'evaluations', ['job_description_id'], unique=False)
    op.create_index('ix_evaluations_ranking', 'evaluations', ['job_description_id', sa.text('overall_score DESC'), sa.text('skill_score DESC'), 'created_at'], unique=False)
    op.create_unique_constraint('uq_evaluations_candidate_job_scoring_version', 'evaluations', ['candidate_id', 'job_description_id', 'scoring_version'])
    op.drop_constraint('fk_evaluations_resume_id_resumes', 'evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_evaluations_candidate_id_candidates'), 'evaluations', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.drop_column('evaluations', 'missing_required_skills')
    op.drop_column('evaluations', 'resume_id')
    op.drop_column('evaluations', 'matched_preferred_skills')
    op.drop_column('evaluations', 'recommendation')
    op.drop_column('evaluations', 'matched_skills')
    op.drop_column('evaluations', 'relevant_experience')
    op.drop_column('evaluations', 'strengths')
    op.drop_column('evaluations', 'fit_level')
    op.drop_column('evaluations', 'concerns')
    op.add_column('job_descriptions', sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('job_descriptions', sa.Column('extraction_version', sa.String(length=50), nullable=False))
    op.add_column('job_descriptions', sa.Column('llm_model', sa.String(length=100), nullable=False))
    op.add_column('job_descriptions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('resumes', sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('resumes', sa.Column('extraction_version', sa.String(length=50), nullable=False))
    op.add_column('resumes', sa.Column('llm_model', sa.String(length=100), nullable=False))
    op.add_column('resumes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('resumes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_resumes_candidate_id', 'resumes', ['candidate_id'], unique=False)
    op.drop_column('resumes', 'uploaded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index('ix_resumes_candidate_id', table_name='resumes')
    op.drop_column('resumes', 'updated_at')
    op.drop_column('resumes', 'created_at')
    op.drop_column('resumes', 'llm_model')
    op.drop_column('resumes', 'extraction_version')
    op.drop_column('resumes', 'structured_data')
    op.drop_column('job_descriptions', 'updated_at')
    op.drop_column('job_descriptions', 'llm_model')
    op.drop_column('job_descriptions', 'extraction_version')
    op.drop_column('job_descriptions', 'structured_data')
    op.add_column('evaluations', sa.Column('concerns', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('evaluations', sa.Column('fit_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('evaluations', sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('evaluations', sa.Column('relevant_experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('evaluations', sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('evaluations', sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('evaluations', sa.Column('matched_preferred_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('evaluations', sa.Column('resume_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('evaluations', sa.Column('missing_required_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_evaluations_candidate_id_candidates'), 'evaluations', type_='foreignkey')
    op.create_foreign_key('fk_evaluations_resume_id_resumes', 'evaluations', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_evaluations_candidate_job_scoring_version', 'evaluations', type_='unique')
    op.drop_index('ix_evaluations_ranking', table_name='evaluations')
    op.drop_index('ix_evaluations_job_description_id', table_name='evaluations')
    op.drop_index('ix_evaluations_candidate_id', table_name='evaluations')
    op.create_unique_constraint('uq_evaluations_resume_job_scoring_version', 'evaluations', ['resume_id', 'job_description_id', 'scoring_version'], postgresql_nulls_not_distinct=False)
    op.drop_column('evaluations', 'updated_at')
    op.drop_column('evaluations', 'llm_explanation')
    op.drop_column('evaluations', 'candidate_id')
    op.create_table('job_requirements',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_description_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('required_experience_years', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('extraction_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('llm_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('extracted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('education_requirements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('domains', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], name='fk_job_requirements_job_description_id_job_descriptions', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_job_requirements'),
    sa.UniqueConstraint('job_description_id', name='uq_job_requirements_job_description_id', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('resume_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resume_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('extraction_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('llm_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('extracted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name='fk_resume_profiles_resume_id_resumes', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_resume_profiles'),
    sa.UniqueConstraint('resume_id', name='uq_resume_profiles_resume_id', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
